### ISSUE TITLE
Not sure, can't load game with Omnia

### ISSUE THREAD

**Issue by EZEILL** [Jozufozu/ExNihiloOmnia#108]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  IC2core (industrialcraft-2-2.6.105-ex110.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.8.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 12/2/16 12:58 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ex Nihilo Omnia (exnihiloomnia)
Caused by: java.lang.NoClassDefFoundError: forestry/core/items/ItemForestry
	at exnihiloomnia.proxy.ClientProxy.preInit(ClientProxy.java:52)
	at exnihiloomnia.ENO.preInitialize(ENO.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: forestry.core.items.ItemForestry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 256239976 bytes (244 MB) / 941809664 bytes (898 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2171 Optifine OptiFine_1.10.2_HD_U_D4 110 mods loaded, 109 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2171.jar) 
	UCH	Forge{12.18.2.2171} [Minecraft Forge] (forge-1.10.2-12.18.2.2171.jar) 
	UCH	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCH	NotEnoughItems{2.1.2.163} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.2.163-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCH	abyssalcraft{1.9.3.8} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.3.8.jar) 
	UCH	actuallyadditions{1.10.2-r85} [Actually Additions] (ActuallyAdditions-1.10.2-r85.jar) 
	UCH	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCH	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCH	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCH	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCH	ichunutil{6.1.0} [iChunUtil] (iChunUtil-1.10.2-6.1.0.jar) 
	UCH	attachablegrinder{6.0.0} [AttachableGrinder] (AttachableGrinder-1.10.2-6.0.0.jar) 
	UCH	autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
	UCH	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	Baubles{1.3.6} [Baubles] (Baubles-1.10.2-1.3.6.jar) 
	UCH	betterbuilderswands{0.7.0} [Better Builder's Wands] (BetterBuildersWands-0.7.0-1.10r148+5479134.jar) 
	UCH	BiomeTweaker{2.1.230} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.230.jar) 
	UCH	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCH	BloodMagic{1.9.4-2.1.0-68} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-68.jar) 
	UCH	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.jar) 
	UCH	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCH	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCH	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UCH	ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter-1.10.2-2.5.6.jar) 
	UCH	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCH	ChickenChunks{2.1.5.42} [ChickenChunks] (ChickenChunks-1.10.2-2.1.5.42-universal.jar) 
	UCH	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCH	chiselsandbits{12.8} [Chisels & Bits] (chiselsandbits-12.8.jar) 
	UCH	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCH	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCH	cyclicmagic{1.8.13} [Cyclic] (Cyclic-1.10.2-1.8.13.jar) 
	UCH	Waila{1.8.0} [Waila] (Hwyla-1.8.1-B13_1.10.2.jar) 
	UCH	darkutils{1.1.6.99} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.99.jar) 
	UCH	eleccore{1.6.345} [ElecCore] (ElecCore-1.10.2-1.6.345.jar) 
	UCH	deepresonance{1.3.1} [DeepResonance] (deepresonance-1.10-1.3.1.jar) 
	UCH	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UCH	elevatorid{1.2.0} [Elevator Mod] (ElevatorMod[V.1.2.0][MC.1.10.2].jar) 
	UCH	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCH	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCH	EnderIO{1.10.2-3.0.1.138_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.138_beta.jar) 
	UCH	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCH	enderutilities{0.6.5} [Ender Utilities] (enderutilities-1.10.2-0.6.5.jar) 
	UCH	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCH	endmetals{1.0.4} [End Metals] (EndMetals_1.9-1.0.4.jar) 
	UCH	IC2{2.6.105-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.105-ex110.jar) 
	UCH	mantle{1.10.2-1.1.2.197} [Mantle] (Mantle-1.10.2-1.1.2.jar) 
	UCH	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCE	exnihiloomnia{1.2.1} [Ex Nihilo Omnia] (exnihiloomnia-1.2.1.jar) 
	UCH	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.10-1.10.2.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.1.jar) 
	UCH	zerocore{1.10.2-0.0.8.1} [Zero CORE] (zerocore-1.10.2-0.0.8.1.jar) 
	UCH	bigreactors{0.4.5.19} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.19.jar) 
	UCH	FlatBedrockx{1.2.1} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.2.1_1.9.4.jar) 
	UCH	gravelminer{4.1.11} [GravelMiner] (GravelMiner_1.10.2-4.1.11.jar) 
	UCH	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCH	Harvest{1.10.2-1.1.0-10} [Harvest] (Harvest-1.10.2-1.1.0-10.jar) 
	UCH	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	irishluck{0.3.3} [Irish Luck] (IrishLuck-0.3.5-MC[1.9.4-1.10-1.10.2].jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	jeresources{0.5.7.96} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.96.jar) 
	UCH	KaishiWeapons{v0.1} [Kaishi's Weapons Pack] (KaishiWeapons-1.9.4.jar) 
	UCH	lootbags{2.2.2} [Loot Bags] (LootBags-1.10.2-2.2.2.jar) 
	UCH	malisiscore{1.10.2-4.2.8} [MalisisCore] (malisiscore-1.10.2-4.2.8.jar) 
	UCH	malisisdoors{1.10.2-5.1.5} [MalisisDoors] (malisisdoors-1.10.2-5.1.5.jar) 
	UCH	mobends{0.22.5} [Mo'Bends] (mobends-0.22.5_for_MC-1.10.2.jar) 
	UCH	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCH	mysticalagriculture{1.3.6} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.3.6.jar) 
	UCH	naturescompass{1.2.0} [Nature's Compass] (NaturesCompass-1.10.2-1.2.0.jar) 
	UCH	nex{1.1.0b} [NetherEx] (NetherEx_1.10.2-1.1.0b.jar) 
	UCH	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCH	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
	UCH	samsocean{1.0.0} [Classic Oceans] (OceanFloor-1.10.2-1.0.1.jar) 
	UCH	OnFurtherTales{2.5.1} [OnFurtherTales] (On Further Tales 2.5.1.jar) 
	UCH	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCH	reborncore{2.8.3.71} [RebornCore] (RebornCore-1.10.2-2.8.3.71-universal.jar) 
	UCH	quantumstorage{3.2.12} [QuantumStorage] (QuantumStorage-1.10.2-3.2.12.jar) 
	UCH	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCH	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCH	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCH	reap{1.3.3} [Reap Mod] (ReapMod 1.3.3.jar) 
	UCH	reborncore-mcmultipart{2.8.3.71} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.8.3.71-universal.jar) 
	UCH	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCH	refinedstorage{1.2.8} [Refined Storage] (refinedstorage-1.2.8.jar) 
	UCH	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCH	RTG{4.1.1.8} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.8.jar) 
	UCH	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5e.jar) 
	UCH	simplegenerators{1.10.2-0.10.5b} [Simple Generators] (simplegenerators-1.10.2-0.10.5b.jar) 
	UCH	simplyconveyors{1.2.0} [Simply Conveyors] (SimplyConveyors-1.1.10.jar) 
	UCH	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	UCH	StevesInferno{2.0} [StevesInferno] (Steves Inferno 2.jar) 
	UCH	supercraftingframe{1.2.1.88} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.88.jar) 
	UCH	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCH	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCH	Translocator{2.1.3.34} [Translocator] (Translocators-1.10.2-2.1.3.34-universal.jar) 
	UCH	trashslot{6.3.7} [TrashSlot] (TrashSlot_1.10.2-6.3.7.jar) 
	UCH	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCH	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCH	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCH	wanionlib{1.10.2-1.2} [WanionLib] (WanionLib-1.10.2-1.2.jar) 
	UCH	waystones{2.0.10} [Waystones] (Waystones_1.10.2-2.0.10.jar) 
	UCH	examplemod{1.0} [Example Mod] (WTF-Expedition_1.10.2_1.2.jar) 
	UCH	wtfcore{1.10.2_v1.1} [wtfcore] (WTF-Expedition_1.10.2_1.2.jar) 
	UCH	UniDict{1.10.2-2.4} [UniDict] (UniDict-1.10.2-2.4.jar) 
	UD	BiomeTweakerCore{2.1.230} [BiomeTweaker Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  codechicken.nei.asm.NEITransformer
IC2core (industrialcraft-2-2.6.105-ex110.jar)
  
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
MalisisCorePlugin (malisiscore-1.10.2-4.2.8.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4474' Renderer: 'Intel(R) HD Graphics 520'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/EZEILL/AppData/Roaming/.minecraft/mods/1.10.2/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4474
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by EZEILL** [comment]
Solved. I'm fairly new to modded minecraft, and forget about an issue someone else posted where it crashes without forestry.
