### ISSUE TITLE
Single Player Client Crash Creating Slime

### ISSUE THREAD

**Issue by FluffyCloud** [Jozufozu/ExNihiloOmnia#119]
I setup a Hopper over a barrel with milk buckets in it and got this crash as soon as I used a bucket of water on the barrel to fill it.

looks like player.capabilities was null?  maybe the player was the hopper in this case?

java.lang.NullPointerException: Ticking block entity
	at exnihiloomnia.blocks.barrels.states.fluid.logic.FluidSummonSlimeTrigger.onUseItem(FluidSummonSlimeTrigger.java:49)
	at exnihiloomnia.blocks.barrels.architecture.BarrelState.useItem(BarrelState.java:49)
	at exnihiloomnia.blocks.barrels.tileentity.TileEntityBarrel$2.insertItem(TileEntityBarrel.java:156)
	at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:129)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:107)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:254)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:202)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:187)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by Jozufozu** [comment]
What version are you on?

**Comment by FluffyCloud** [comment]
Playing skyexchange off of curse, pack version 1.2.4, minecraft version 1.10.2, forge version 12.18.2.2171, and the mod file is called...  exnihiloomina-1.2.0.jar

**Comment by FluffyCloud** [comment]
And when i updated exnihiloomina-1.2.1.jar it gave me this on startup instead of the previous crash log:

// Don't be sad, have a hug! <3

Time: 12/11/16 10:10 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ex Nihilo Omnia (exnihiloomnia)
Caused by: java.lang.NoClassDefFoundError: forestry/core/items/ItemForestry
	at exnihiloomnia.proxy.ClientProxy.preInit(ClientProxy.java:52)
	at exnihiloomnia.ENO.preInitialize(ENO.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: forestry.core.items.ItemForestry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: java.lang.NullPointerException

**Comment by Jozufozu** [comment]
I've been working on this for the last hour, and the only solution I can come up with that doesn't involve milk duplication is just not letting pipes or hoppers make slime. I'll think about it more, but that is worst-case scenario.

**Comment by FluffyCloud** [comment]
your issue is that a hopper or pipe isn't a player, but the only reason you need to know if it's a player is to give back the correct type of bucket, right?  

how about just eating the bucket entirely if you can't find a player to return a bucket to?  it's not a *good* fix, but at least it wouldn't be game-breaking.

**Comment by FluffyCloud** [comment]
Updated mod, confirm this fixes my savegame. thanks!! :)
