### ISSUE TITLE
NPE during BlockBarrel.removedbyPlayer event

### ISSUE THREAD

**Issue by Vaygrim** [Jozufozu/ExNihiloOmnia#120]
MC 1.10.2
Ex Nihilo Omni 1.2.0

We are getting a NullPointerException being thrown in the server logs when ever a player tries to break a placed Barrel from Ex Nihilo Omnia. Result is that the player is unable to break or remove the barrel at all. They have to use fire / lava to burn the wooden barrels to clear them.

Let me know if you need extensive logs / whatnot.

Caused by: java.lang.NullPointerException
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:66) ~[yk.class:?]
	at exnihiloomnia.util.helpers.InventoryHelper.dropItemInWorld(InventoryHelper.java:29) ~[InventoryHelper.class:?]
	at exnihiloomnia.blocks.barrels.BlockBarrel.removedByPlayer(BlockBarrel.java:110) ~[BlockBarrel.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:275) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:333) ~[lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
>

**Comment by SDUBZ** [comment]
vaygrim have you tried updating to 1.2.1 because i believe this is fixed in the newer version i had the same problem with my skyblock pack

**Comment by Vaygrim** [comment]
Pack update coming to the Test Server within the next few days, yes. I will report back and see if this gets resolved!
