### ISSUE TITLE
[1.12.2] Crashing at mod-load time - java.lang.NoClassDefFoundError: kotlin/streams/jdk8/StreamsKt

### ISSUE THREAD

**Issue by ghost** [Jozufozu/ExNihiloOmnia#166]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.3.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 11/21/19 9:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ex Nihilo Omnia (exnihiloomnia)

Caused by: java.lang.NoClassDefFoundError: kotlin/streams/jdk8/StreamsKt

	at com.jozufozu.exnihiloomnia.common.registries.RegistryLoader.getFilesToLoad(RegistryLoader.kt:111)

	at com.jozufozu.exnihiloomnia.common.registries.RegistryLoader.genericLoad(RegistryLoader.kt:63)

	at com.jozufozu.exnihiloomnia.common.registries.RegistryManager$ORES$1.invoke(RegistryManager.kt:20)

	at com.jozufozu.exnihiloomnia.common.registries.RegistryManager$ORES$1.invoke(RegistryManager.kt:19)

	at com.jozufozu.exnihiloomnia.common.registries.ReloadableRegistry.load(ReloadableRegistry.kt:31)

	at com.jozufozu.exnihiloomnia.common.registries.RegistryLoader.loadOres(RegistryLoader.kt:33)

	at com.jozufozu.exnihiloomnia.proxy.CommonProxy.preInit(CommonProxy.kt:31)

	at com.jozufozu.exnihiloomnia.proxy.ClientProxy.preInit(ClientProxy.kt:36)

	at com.jozufozu.exnihiloomnia.ExNihilo.preInit(ExNihilo.kt:43)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)

	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)

	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)

	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)

	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)

	at net.minecraft.client.main.Main.main(SourceFile:123)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Caused by: java.lang.ClassNotFoundException: kotlin.streams.jdk8.StreamsKt

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	... 49 more

Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 481933240 bytes (459 MB) / 1744830464 bytes (1664 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                          | Signature                                |
	|:----- |:------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCH   | mcp                 | 9.42                     | minecraft.jar                                   | None                                     |
	| LCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCH   | forge               | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCH   | uncraftingtable     | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar             | None                                     |
	| LCH   | actuallyadditions   | 1.12.2-r151              | ActuallyAdditions-1.12.2-r151.jar               | None                                     |
	| LCH   | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCH   | betterbuilderswands | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| LCH   | bookshelf           | 2.3.589                  | Bookshelf-1.12.2-2.3.589.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | jei                 | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                       | None                                     |
	| LCH   | botania             | r1.10-361                | Botania+r1.10-361.jar                           | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                | None                                     |
	| LCH   | ceramics            | 1.12-1.3.7               | Ceramics-1.12-1.3.7.jar                         | None                                     |
	| LCH   | chameleon           | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCH   | chesttransporter    | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| LCH   | chickens            | 6.0.4                    | chickens-6.0.4.jar                              | None                                     |
	| LCH   | codechickenlib      | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | cyclopscore         | 1.5.1                    | CyclopsCore-1.12.2-1.5.1.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | colossalchests      | 1.7.2                    | ColossalChests-1.12.2-1.7.2.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | controlling         | 3.0.7                    | Controlling-3.0.7.jar                           | None                                     |
	| LCH   | cucumber            | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                       | None                                     |
	| LCH   | eplus               | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCE   | exnihiloomnia       | 1.0                      | exnihiloomnia_1.12.2-0.0.2.jar                  | None                                     |
	| LC    | excompressum        | 3.0.31                   | ExCompressum_1.12.2-3.0.31.jar                  | None                                     |
	| LC    | extraanvils         | @VERSION@                | extraanvils-0.9.jar                             | None                                     |
	| LC    | extrautils2         | 1.0                      | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| LC    | fluidfunnel         | 1.2.0                    | FluidFunnel-1.12.2-1.2.0.jar                    | None                                     |
	| LC    | forgelin            | 1.8.3                    | Forgelin-1.8.3.jar                              | None                                     |
	| LC    | gravestone          | 1.10.2                   | gravestone-1.10.2.jar                           | None                                     |
	| LC    | hatchery            | 2.2.2                    | hatchery-1.12.2-2.2.2.jar                       | None                                     |
	| LC    | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LC    | placebo             | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                        | None                                     |
	| LC    | hydrogel            | 1.1.0                    | HydroGel-1.12.2-1.1.0.jar                       | None                                     |
	| LC    | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironbackpacks       | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| LC    | ironchest           | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LC    | kleeslabs           | 5.4.12                   | KleeSlabs_1.12.2-5.4.12.jar                     | None                                     |
	| LC    | literalascension    | 1.12.2-1.0.2.2           | literalascension-1.12.2-2.0.0.0.jar             | None                                     |
	| LC    | mcjtylib_ng         | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                         | None                                     |
	| LC    | missing_pieces      | 4.3.0                    | missing_pieces-1.12.2-4.3.0.jar                 | None                                     |
	| LC    | morechickens        | 3.1.0                    | morechickens-1.12.2-3.1.0.jar                   | None                                     |
	| LC    | mysticalagriculture | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar            | None                                     |
	| LC    | nei                 | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | harvestcraft        | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2ze.jar                 | None                                     |
	| LC    | randomthings        | 4.2.7.3                  | RandomThings-MC1.12.2-4.2.7.3.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | redstonepaste       | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                  | None                                     |
	| LC    | rftools             | 7.72                     | rftools-1.12-7.72.jar                           | None                                     |
	| LC    | snad                | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                      | None                                     |
	| LC    | storagedrawers      | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                 | None                                     |
	| LC    | tp                  | 3.2.34                   | tinyprogressions-1.12.2-3.3.34-Release.jar      | None                                     |
	| LC    | torchmaster         | 1.8.1.81                 | torchmaster_1.12.2-1.8.1.81.jar                 | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LC    | treechopper         | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13571 Compatibility Profile Context 19.9.3 26.20.13025.1004' Renderer: 'AMD Radeon R9 200 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by Jozufozu** [comment]
Updating [forgelin](https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin/files/2785465) should fix it
