### ISSUE TITLE
Crash - Collecting Water

### ISSUE THREAD

**Issue by RobertLSnead** [Jozufozu/ExNihiloOmnia#84]
I get the following error when collecting water with a bucket:

java.lang.NullPointerException: Unexpected error
	at exnihiloomnia.items.ENOBucketHandler.bucketFill(ENOBucketHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_646_ENOBucketHandler_bucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:336)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at exnihiloomnia.items.ENOBucketHandler.bucketFill(ENOBucketHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_646_ENOBucketHandler_bucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:336)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

**Comment by Syndaryl** [comment]
Sounds like #82 and #83 - This should be fixed in the next version.
